// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp1cX6g_On5XMWXwfcTFM-7aMU23bXYcE',
    appId: '1:238926343669:web:017556708ff1ec1e6684bc',
    messagingSenderId: '238926343669',
    projectId: 'fir-89272',
    authDomain: 'fir-89272.firebaseapp.com',
    storageBucket: 'fir-89272.firebasestorage.app',
    measurementId: 'G-KNKP7CLE52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_fsOy8FxmMlihEmdhz4iMLYphHUox7U',
    appId: '1:238926343669:android:76ed9274cba9e93b6684bc',
    messagingSenderId: '238926343669',
    projectId: 'fir-89272',
    storageBucket: 'fir-89272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0O3ogUj9y1h-1ucwckqEHAlkfD7B50Sc',
    appId: '1:238926343669:ios:75881170bdc4c1966684bc',
    messagingSenderId: '238926343669',
    projectId: 'fir-89272',
    storageBucket: 'fir-89272.firebasestorage.app',
    androidClientId: '238926343669-979sf6bg6ghitrg193qgvb3pdtdaksbb.apps.googleusercontent.com',
    iosClientId: '238926343669-hd8do778ao2pqu9i0no67qjea95qfj7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0O3ogUj9y1h-1ucwckqEHAlkfD7B50Sc',
    appId: '1:238926343669:ios:75881170bdc4c1966684bc',
    messagingSenderId: '238926343669',
    projectId: 'fir-89272',
    storageBucket: 'fir-89272.firebasestorage.app',
    androidClientId: '238926343669-979sf6bg6ghitrg193qgvb3pdtdaksbb.apps.googleusercontent.com',
    iosClientId: '238926343669-hd8do778ao2pqu9i0no67qjea95qfj7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp1cX6g_On5XMWXwfcTFM-7aMU23bXYcE',
    appId: '1:238926343669:web:8a3199d8a0473deb6684bc',
    messagingSenderId: '238926343669',
    projectId: 'fir-89272',
    authDomain: 'fir-89272.firebaseapp.com',
    storageBucket: 'fir-89272.firebasestorage.app',
    measurementId: 'G-3XBPL2CN3J',
  );
}
